import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import { Sidetray } from "./components/layout/Sidetray/Sidetray";
import { Header } from "./components/layout/Header/Header";
import { WasmProvider } from "./providers/WasmProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WasmProvider>
            <main className="flex h-screen">
              <Sidetray />
              <div className="bg-background w-full h-screen flex flex-col">
                <Header />

                {children}
              </div>
            </main>
          </WasmProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
